$(document).ready(function(){
    $("#pdesign").click(function(){
      $("#pdesign").hide();
      $("#pdesign2").show();
  });
  $("#pdesign2").click(function(){
    $("#pdesign2").slideUp();
    $("#pdesign").slideDown();
  });
  });
  
  $(document).ready(function(){
    $("#pdevelopment").click(function(){
      $("#pdevelopment").hide();
      $("#pdevelopment2").show();
  });
  $("#pdevelopment2").click(function(){
    $("#pdevelopment2").slideUp();
    $("#pdevelopment").slideDown();
  });
  });
  $(document).ready(function(){
    $("#product").click(function(){
      $("#product").hide();
      $("#product2").show();
  });
  $("#product2").click(function(){
    $("#product2").slideUp();
    $("#product").slideDown();
  });
  });
  


  $(document).ready(function(){
    $("#gray_background").mouseover(function(){
      $("#white_front0").show();
    }).mouseout(function(){
        $("#white_front0").hide();
    });
    $("#ontario").mouseover(function(){
      $("#white_front1").show();
    }).mouseout(function(){
        $("#white_front1").hide();
    });
 });
 $(document).ready(function(){
    $("#orange_brown").mouseover(function(){
      $("#white_front2").show();
    }).mouseout(function(){
        $("#white_front2").hide();
    });
    $("#jim_carey_").mouseover(function(){
      $("#white_front3").show();
    }).mouseout(function(){
        $("#white_front3").hide();
    });
 });
 $(document).ready(function(){
    $("#work5_1").mouseover(function(){
      $("#white_front4").show();
    }).mouseout(function(){
        $("#white_front4").hide();
    });
    $("#work6_1").mouseover(function(){
      $("#white_front5").show();
    }).mouseout(function(){
        $("#white_front5").hide();
    });
    $("#work7_1").mouseover(function(){
      $("#white_front6").show();
    }).mouseout(function(){
        $("#white_front6").hide();
    });
    $("#work8_1").mouseover(function(){
      $("#white_front7").show();
    }).mouseout(function(){
        $("#white_front7").hide();
    });
 });
 
function popup(){
    swal("Oops!", "Message not Sent", "error");
    } 